# [Aassignment 4 solution Reference](https://www.kaggle.com/kylingu/apply-machine-learning-module-4-assignment)

In [67]:
import pandas as pd
import numpy as np
import os

df_train = pd.read_csv('train.csv', encoding = 'ISO-8859-1', low_memory=False).set_index('ticket_id')
df_address = pd.read_csv('addresses.csv', encoding = 'ISO-8859-1', low_memory=False).set_index('ticket_id')

In [68]:
df_train.head(5).T

ticket_id,22056,27586,22062,22084,22093
agency_name,"Buildings, Safety Engineering & Env Department","Buildings, Safety Engineering & Env Department","Buildings, Safety Engineering & Env Department","Buildings, Safety Engineering & Env Department","Buildings, Safety Engineering & Env Department"
inspector_name,"Sims, Martinzie","Williams, Darrin","Sims, Martinzie","Sims, Martinzie","Sims, Martinzie"
violator_name,"INVESTMENT INC., MIDWEST MORTGAGE","Michigan, Covenant House","SANDERS, DERRON","MOROSI, MIKE","NATHANIEL, NEAL"
violation_street_number,2900,4311,1449,1441,2449
violation_street_name,TYLER,CENTRAL,LONGFELLOW,LONGFELLOW,CHURCHILL
violation_zip_code,NaN,NaN,NaN,NaN,NaN
mailing_address_str_number,3,2959,23658,5,7449
mailing_address_str_name,S. WICKER,Martin Luther King,P.O. BOX,ST. CLAIR,CHURCHILL
city,CHICAGO,Detroit,DETROIT,DETROIT,DETROIT
state,IL,MI,MI,MI,MI
zip_code,60606,48208,48223,48214,48206
non_us_str_code,NaN,NaN,NaN,NaN,NaN
country,USA,USA,USA,USA,USA
ticket_issued_date,2004-03-16 11:40:00,2004-04-23 12:30:00,2004-04-26 13:40:00,2004-04-26 13:30:00,2004-04-26 13:00:00
hearing_date,2005-03-21 10:30:00,2005-05-06 13:30:00,2005-03-29 10:30:00,NaN,2005-03-29 10:30:00
violation_code,9-1-36(a),61-63.0600,9-1-36(a),9-1-36(a),9-1-36(a)
violation_description,Failure of owner to obtain certificate of comp...,Failed To Secure Permit For Lawful Use Of Buil...,Failure of owner to obtain certificate of comp...,Failure of owner to obtain certificate of comp...,Failure of owner to obtain certificate of comp...
disposition,Responsible by Default,Responsible by Determination,Not responsible by Dismissal,Not responsible by City Dismissal,Not responsible by Dismissal
fine_amount,250,750,250,250,250
admin_fee,20,20,0,0,0
state_fee,10,10,0,0,0
late_fee,25,75,0,0,0
discount_amount,0,0,0,0,0
clean_up_cost,0,0,0,0,0
judgment_amount,305,855,0,0,0
payment_amount,0,780,0,0,0
balance_due,305,75,0,0,0
payment_date,NaN,2005-06-02 00:00:00,NaN,NaN,NaN
payment_status,NO PAYMENT APPLIED,PAID IN FULL,NO PAYMENT APPLIED,NO PAYMENT APPLIED,NO PAYMENT APPLIED
collection_status,NaN,NaN,NaN,NaN,NaN
grafitti_status,NaN,NaN,NaN,NaN,NaN
compliance_detail,non-compliant by no payment,compliant by late payment within 1 month,not responsible by disposition,not responsible by disposition,not responsible by disposition
compliance,0,1,NaN,NaN,NaN

In [69]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 250306 entries, 22056 to 325561
Data columns (total 33 columns):
agency_name                   250306 non-null object
inspector_name                250306 non-null object
violator_name                 250272 non-null object
violation_street_number       250306 non-null float64
violation_street_name         250306 non-null object
violation_zip_code            0 non-null float64
mailing_address_str_number    246704 non-null float64
mailing_address_str_name      250302 non-null object
city                          250306 non-null object
state                         250213 non-null object
zip_code                      250305 non-null object
non_us_str_code               3 non-null object
country                       250306 non-null object
ticket_issued_date            250306 non-null object
hearing_date                  237815 non-null object
violation_code                250306 non-null object
violation_description         250306 non-null object
disposition                   250306 non-null object
fine_amount                   250305 non-null float64
admin_fee                     250306 non-null float64
state_fee                     250306 non-null float64
late_fee                      250306 non-null float64
discount_amount               250306 non-null float64
clean_up_cost                 250306 non-null float64
judgment_amount               250306 non-null float64
payment_amount                250306 non-null float64
balance_due                   250306 non-null float64
payment_date                  41113 non-null object
payment_status                250306 non-null object
collection_status             36897 non-null object
grafitti_status               1 non-null object
compliance_detail             250306 non-null object
compliance                    159880 non-null float64
dtypes: float64(13), object(20)
memory usage: 64.9+ MB

In [70]:
df_train.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
agency_name,250306,5,"Buildings, Safety Engineering & Env Department",157784,NaN,NaN,NaN,NaN,NaN,NaN,NaN
inspector_name,250306,173,"Morris, John",17926,NaN,NaN,NaN,NaN,NaN,NaN,NaN
violator_name,250272,119992,"INVESTMENT, ACORN",809,NaN,NaN,NaN,NaN,NaN,NaN,NaN
violation_street_number,250306,NaN,NaN,NaN,10649.9,31887.3,0,4739,10244,15760,1.41541e+07
violation_street_name,250306,1791,SEVEN MILE,3482,NaN,NaN,NaN,NaN,NaN,NaN,NaN
violation_zip_code,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mailing_address_str_number,246704,NaN,NaN,NaN,9149.79,36020.3,1,544,2456,12927.2,5.11134e+06
mailing_address_str_name,250302,37896,PO BOX,8668,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,250306,5184,DETROIT,136936,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state,250213,59,MI,228601,NaN,NaN,NaN,NaN,NaN,NaN,NaN
zip_code,250305,4251,48227,11617,NaN,NaN,NaN,NaN,NaN,NaN,NaN
non_us_str_code,3,2,"ONTARIO, Canada",2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,250306,5,USA,250293,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ticket_issued_date,250306,86979,2010-02-17 09:00:00,97,NaN,NaN,NaN,NaN,NaN,NaN,NaN
hearing_date,237815,6222,2005-12-22 10:30:00,622,NaN,NaN,NaN,NaN,NaN,NaN,NaN
violation_code,250306,235,9-1-36(a),99091,NaN,NaN,NaN,NaN,NaN,NaN,NaN
violation_description,250306,258,Failure of owner to obtain certificate of comp...,99091,NaN,NaN,NaN,NaN,NaN,NaN,NaN
disposition,250306,9,Responsible by Default,138340,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fine_amount,250305,NaN,NaN,NaN,374.423,707.196,0,200,250,250,10000
admin_fee,250306,NaN,NaN,NaN,12.7748,9.60734,0,0,20,20,20
state_fee,250306,NaN,NaN,NaN,6.38738,4.80367,0,0,10,10,10
late_fee,250306,NaN,NaN,NaN,21.4945,56.4643,0,0,10,25,1000
discount_amount,250306,NaN,NaN,NaN,0.125167,3.43018,0,0,0,0,350
clean_up_cost,250306,NaN,NaN,NaN,0,0,0,0,0,0,0
judgment_amount,250306,NaN,NaN,NaN,268.685,626.915,0,0,140,305,11030
payment_amount,250306,NaN,NaN,NaN,48.899,222.422,0,0,0,0,11075
balance_due,250306,NaN,NaN,NaN,222.449,606.394,-7750,0,25,305,11030
payment_date,41113,2307,2014-08-04 00:00:00,177,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_status,250306,3,NO PAYMENT APPLIED,209193,NaN,NaN,NaN,NaN,NaN,NaN,NaN
collection_status,36897,1,IN COLLECTION,36897,NaN,NaN,NaN,NaN,NaN,NaN,NaN
grafitti_status,1,1,GRAFFITI TICKET,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
compliance_detail,250306,10,non-compliant by no payment,129267,NaN,NaN,NaN,NaN,NaN,NaN,NaN
compliance,159880,NaN,NaN,NaN,0.0725357,0.259374,0,0,0,0,1

In [71]:
df_address.head(7).T

ticket_id,22056,27586,22062,22084,22093,22046,18738
address,"2900 tyler, Detroit MI","4311 central, Detroit MI","1449 longfellow, Detroit MI","1441 longfellow, Detroit MI","2449 churchill, Detroit MI","6478 northfield, Detroit MI","8027 brentwood, Detroit MI"

In [72]:
df_address.describe().T

          count  unique                        top freq
address  311307  121769  1509 broadway, Detroit MI  203

In [73]:
# Extract city and state from the address DF
city, state= zip(*df_address.address.apply(lambda x: x.split(', ')[1].split(' ')))

city[0:5], state[0:5]

(('Detroit', 'Detroit', 'Detroit', 'Detroit', 'Detroit'),
 ('MI', 'MI', 'MI', 'MI', 'MI'))

In [74]:
# create violation address DF 
violation_address = pd.DataFrame({'vio_city': city, 'vio_state': state}, index=df_address.index)
violation_address.describe(include='all').T

            count unique      top    freq
vio_city   311307      1  Detroit  311307
vio_state  311307      1       MI  311307

In [75]:
# Compliance column values and their percentages
df_train.compliance.value_counts(dropna=False)/len(df_train)

 0.0    0.592407
NaN     0.361262
 1.0    0.046331
Name: compliance, dtype: float64

The compliance field contains too much `NaN`, about $36\%$.  Too much to be dropped.

In [76]:
# Treat NaN value as 0.0 assume that they are compliant
df_train_all = df_train.copy()
df_train = df_train.dropna(subset=['compliance'])

df_train.compliance.value_counts(dropna=False)/len(df_train)

0.0    0.927464
1.0    0.072536
Name: compliance, dtype: float64

__Analyze fileds might be used for the model__

In [77]:
df_train.groupby('agency_name').groups.keys()

dict_keys(['Buildings, Safety Engineering & Env Department', 'Department of Public Works', 'Detroit Police Department', 'Health Department', 'Neighborhood City Halls'])

In [78]:
df_train.groupby('agency_name').compliance.agg(['count', 'sum', 'mean', 'std']).T
# From mean, Detroit Police Department offers >13% => more people paid

agency_name,"Buildings, Safety Engineering & Env Department",Department of Public Works,Detroit Police Department,Health Department,Neighborhood City Halls
count,95863.000000,52445.000000,4464.000000,7107.000000,1.0
sum,5823.000000,4718.000000,588.000000,468.000000,0.0
mean,0.060743,0.089961,0.131720,0.065851,0.0
std,0.238859,0.286128,0.338224,0.248038,NaN

In [79]:
len(df_train.groupby('inspector_name').groups)
# too many to be useful

159

In [80]:
df_train.groupby('disposition').compliance.agg(['count', 'sum', 'mean', 'std']).T

disposition,Responsible (Fine Waived) by Deter,Responsible by Admission,Responsible by Default,Responsible by Determination
count,195.0,13701.000000,138340.000000,7644.000000
sum,195.0,3768.000000,5285.000000,2349.000000
mean,1.0,0.275016,0.038203,0.307300
std,0.0,0.446539,0.191687,0.461405

In [81]:
df_train.groupby('country').compliance.agg(['count', 'sum', 'mean', 'std']).T

country      Aust  Cana      Egyp  Germ            USA
count    2.000000   6.0  2.000000   1.0  159869.000000
sum      1.000000   0.0  1.000000   0.0   11595.000000
mean     0.500000   0.0  0.500000   0.0       0.072528
std      0.707107   0.0  0.707107   NaN       0.259361

In [82]:
len(df_train.groupby('state').groups)
# almost all states and from other countries

59

In [83]:
df_train.groupby('violation_code').groups.keys()

dict_keys(['19420901', '19450901', '19830901', '19840901', '19850901', '20130901', '20160901', '20180901', '22-2-16', '22-2-17', '22-2-17(a)', '22-2-18', '22-2-20', '22-2-21(a)', '22-2-21(b)', '22-2-22', '22-2-22(a)', '22-2-23', '22-2-38', '22-2-41', '22-2-42', '22-2-43', '22-2-44', '22-2-45', '22-2-49', '22-2-49(a)', '22-2-49(b)', '22-2-49(c)', '22-2-49(d)', '22-2-53', '22-2-55', '22-2-56', '22-2-61', '22-2-83', '22-2-83(a)(b)(c)', '22-2-83(b)', '22-2-83(c)', '22-2-83(d)', '22-2-84 (DO NOT USE ', '22-2-84(a)', '22-2-84(a)(1)(2)(4)', '22-2-84(b)(3)', '22-2-85', '22-2-87', '22-2-87(a)', '22-2-88', '22-2-88(a)', '22-2-88(b)', '22-2-91', '22-2-93', '22-2-94', '22-2-96', '22-2-97(b)', '22-3-2', '61-101.0100/32.0066', '61-104.0100', '61-111.0100/32.0066', '61-114.0100', '61-118.0100/32.0066', '61-120.0100/32.0066', '61-121.0100/32.0066', '61-130.0000/130.0400', '61-130.0000/130.0500', '61-4-32', '61-4-33', '61-4-35', '61-4-37', '61-45.0000/45.0800', '61-47.0000/47.0108', '61-5-18', '61-5-19', '61-5-21', '61-63.0100', '61-63.0500', '61-63.0600', '61-8-127', '61-8-27', '61-8-47', '61-80.0100', '61-81.0100/32.0066', '61-81.0100/45.0807', '61-82.0100/32.0031', '61-82.0100/32.0066', '61-83.0100/32.0031', '61-83.0100/32.0066', '61-84.0100/32.0066', '61-84.0100/45.0807', '61-86.0100/32.0066', '61-86.0100/32.0076B', '61-86.0100/45.0807', '61-90.0100', '9-1-101', '9-1-102', '9-1-103 (a) or (b)', '9-1-103(C)', '9-1-104', '9-1-105', '9-1-106', '9-1-107', '9-1-108', '9-1-109', '9-1-110(a)', '9-1-110(b)', '9-1-111', '9-1-112', '9-1-113', '9-1-12(b)', '9-1-201(a)', '9-1-201(b)', '9-1-202', '9-1-203', '9-1-204', '9-1-205', '9-1-206', '9-1-207', '9-1-208', '9-1-209', '9-1-210', '9-1-211', '9-1-212', '9-1-213', '9-1-214', '9-1-216', '9-1-219', '9-1-220', '9-1-221', '9-1-301', '9-1-303', '9-1-304', '9-1-305', '9-1-306', '9-1-307', '9-1-309', '9-1-310', '9-1-311', '9-1-331', '9-1-332', '9-1-333', '9-1-351', '9-1-352', '9-1-353(2)', '9-1-354', '9-1-355', '9-1-36(a)', '9-1-36(c)', '9-1-36(d)', '9-1-375', '9-1-377', '9-1-405', '9-1-406', '9-1-43(a) - (Dwellin', '9-1-43(a) - (Stories', '9-1-43(a) - (Structu', '9-1-432(a)', '9-1-434', '9-1-439', '9-1-440', '9-1-441', '9-1-441(a)', '9-1-442', '9-1-443(a)', '9-1-443(b)', '9-1-45(b)', '9-1-45(c)', '9-1-46(a)', '9-1-462(a)', '9-1-464', '9-1-465', '9-1-468', '9-1-469', '9-1-474', '9-1-476', '9-1-477', '9-1-478', '9-1-50 (e)', '9-1-50(a)', '9-1-50(b)', '9-1-502', '9-1-503', '9-1-81(a)', '9-1-81(b)', '9-1-81(e)', '9-1-82(b)', '9-1-82(d) - (Buildin', '9-1-82(d) - (Dwellin', '9-1-82(d) - (Structu', '9-1-83 - (Building 5', '9-1-83 - (Dwelling)', '9-1-83 - (Structures'])

In [84]:
len(df_train.groupby('violation_code').groups.keys())

189

In [85]:
df_train.groupby('disposition').compliance.agg(['count', 'sum', 'mean', 'std']).T

disposition,Responsible (Fine Waived) by Deter,Responsible by Admission,Responsible by Default,Responsible by Determination
count,195.0,13701.000000,138340.000000,7644.000000
sum,195.0,3768.000000,5285.000000,2349.000000
mean,1.0,0.275016,0.038203,0.307300
std,0.0,0.446539,0.191687,0.461405

__Analyze the `disposition` field__

In [86]:
print("Original disposition values= \n{} \n\nCompliance disposition values= \n{}".format(
    df_train_all.disposition.unique(), df_train.disposition.unique()))

Original disposition values=
['Responsible by Default' 'Responsible by Determination'
 'Not responsible by Dismissal' 'Not responsible by City Dismissal'
 'PENDING JUDGMENT' 'Responsible by Admission'
 'Not responsible by Determination' 'SET-ASIDE (PENDING JUDGMENT)'
 'Responsible (Fine Waived) by Deter']

Compliance disposition values=
['Responsible by Default' 'Responsible by Determination'
 'Responsible by Admission' 'Responsible (Fine Waived) by Deter']

In [88]:
# Consolidate the various disposition values to several classes
disposition_replace = {'Responsible by Default': 'By default',
                       'Responsible by Determination': 'By determination', 
                       'Responsible (Fine Waived) by Deter': 'Fine Waived',
                       'Responsible by Admission': 'By admission',
                       'SET-ASIDE (PENDING JUDGMENT)': 'Pending',
                       'PENDING JUDGMENT': 'Pending',
                       'Not responsible by Dismissal': 'Not responsible',
                       'Not responsible by City Dismissal': 'Not responsible',
                       'Not responsible by Determination': 'Not responsible'
                      }

df_train_all.disposition.replace(disposition_replace, inplace=True)
df_train_all.groupby('disposition').compliance.agg(['count', 'sum', 'mean', 'std']).T

disposition,By admission,By default,By determination,Fine Waived,Not responsible,Pending
count,13701.000000,138340.000000,7644.000000,195.0,0.0,0.0
sum,3768.000000,5285.000000,2349.000000,195.0,NaN,NaN
mean,0.275016,0.038203,0.307300,1.0,NaN,NaN
std,0.446539,0.191687,0.461405,0.0,NaN,NaN